"""empty message

Revision ID: 01d0a6ab19e9
Revises: 047b6ee0e9b2
Create Date: 2026-08-23 11:53:19.303757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d0a6ab19e9'
down_revision = '047b6ee0e9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.String(length=10), nullable=False))
        batch_op.drop_column('Sport')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sport', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('sport')

    # ### end Alembic commands ###
