"""empty message

Revision ID: 047b6ee0e9b2
Revises: 4ff8517b0c61
Create Date: 2026-08-16 23:43:05.449669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047b6ee0e9b2'
down_revision = '4ff8517b0c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_reason', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('status_reason')

    # ### end Alembic commands ###
