"""empty message

Revision ID: 05a74461507a
Revises: be06a84aab07
Create Date: 2026-05-31 12:45:15.451267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a74461507a'
down_revision = 'be06a84aab07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payments_deal_id', 'deals', ['deal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_deal_id', type_='foreignkey')
        batch_op.drop_column('deal_id')

    # ### end Alembic commands ###
