"""empty message

Revision ID: 11233b8b6c66
Revises: ab7e0e4bf17a
Create Date: 2026-06-15 11:42:15.500679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11233b8b6c66'
down_revision = 'ab7e0e4bf17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
