"""empty message

Revision ID: 146722d01960
Revises: a573303c7bbc
Create Date: 2026-03-13 23:50:09.568193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146722d01960'
down_revision = 'a573303c7bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.drop_column('car')

    # ### end Alembic commands ###
