"""empty message

Revision ID: 159ea51dc8b9
Revises: b2dddc593144
Create Date: 2026-09-01 22:47:22.846120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159ea51dc8b9'
down_revision = 'b2dddc593144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
