"""empty message

Revision ID: 1fda0b7a245e
Revises: 96e5e75e3f45
Create Date: 2026-01-09 22:48:03.866526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fda0b7a245e'
down_revision = '96e5e75e3f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aboutme', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('aboutme')

    # ### end Alembic commands ###
