"""empty message

Revision ID: 214111ca8418
Revises: 53d082275109
Create Date: 2026-04-10 10:04:00.551554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214111ca8418'
down_revision = '53d082275109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('ad_info',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serv_charge', sa.Float(precision=2), nullable=False))
        batch_op.add_column(sa.Column('rzerv_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['booking_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])
        batch_op.drop_column('primary_guest')
        batch_op.drop_column('pguest_phone')
        batch_op.drop_column('pguest_email')
        batch_op.drop_column('room_id')
        batch_op.drop_column('ad_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_info', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pguest_email', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('pguest_phone', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('primary_guest', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('rzerv_points')
        batch_op.drop_column('serv_charge')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('ad_info',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
