"""empty message

Revision ID: 3297b59279b8
Revises: c275745b9b27
Create Date: 2026-03-07 21:02:35.157602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3297b59279b8'
down_revision = 'c275745b9b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('max_occupancy',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('max_occupancy',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
