"""empty message

Revision ID: 33078104f87b
Revises: e73bc1ca5e34
Create Date: 2026-05-25 13:45:21.378550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33078104f87b'
down_revision = 'e73bc1ca5e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
