"""empty message

Revision ID: 36709e9d8e2b
Revises: f93f313e66df
Create Date: 2026-07-15 09:53:33.175972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36709e9d8e2b'
down_revision = 'f93f313e66df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
