"""empty message

Revision ID: 38808e1896a6
Revises: 8a8985e45784
Create Date: 2026-04-15 12:41:37.340706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38808e1896a6'
down_revision = '8a8985e45784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('serv_charge',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('serv_charge',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
