"""empty message

Revision ID: 3d912cd3fb44
Revises: 43efc77d6858
Create Date: 2026-08-27 20:25:43.317224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d912cd3fb44'
down_revision = '43efc77d6858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rooms')
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.alter_column('sms_fee_host',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('sms_fee_gbp',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('sms_notifications_enabled')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.alter_column('sms_fee_gbp',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('sms_fee_host',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    op.create_table('_alembic_tmp_rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('room_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('room_location', sa.VARCHAR(length=30), nullable=False),
    sa.Column('room_country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('room_category', sa.VARCHAR(length=30), nullable=False),
    sa.Column('image1', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image2', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image3', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image4', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image5', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image6', sa.VARCHAR(length=20), nullable=False),
    sa.Column('short_desc', sa.VARCHAR(length=100), nullable=False),
    sa.Column('room_size', sa.VARCHAR(length=20), nullable=False),
    sa.Column('max_occupancy', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rule1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rule2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rule3', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('room_currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('borough', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content_language', sa.VARCHAR(length=5), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_room_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_room_longitude_range')),
    sa.CheckConstraint('max_occupancy > 0', name=op.f('ck_room_occupancy_positive')),
    sa.CheckConstraint('price > 0', name=op.f('ck_room_price_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_name', name=op.f('uq_room_name_per_host'))
    )
    # ### end Alembic commands ###
