"""empty message

Revision ID: 3faccc5b6bd6
Revises: d2a066642779
Create Date: 2026-03-14 12:24:54.888952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faccc5b6bd6'
down_revision = 'd2a066642779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.alter_column('car',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.alter_column('car',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
