"""empty message

Revision ID: 3fdbc80ce19b
Revises: 
Create Date: 2025-12-31 15:13:29.635278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdbc80ce19b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('country')

    # ### end Alembic commands ###
