"""empty message

Revision ID: 412898959584
Revises: ffdf3a4ba260
Create Date: 2026-05-10 21:23:19.226155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412898959584'
down_revision = 'ffdf3a4ba260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=False),
    sa.Column('pay_method', sa.VARCHAR(length=30), nullable=False),
    sa.Column('price_per_night', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('book_days', sa.INTEGER(), nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('total_paid', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('rzerv_points', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('voucher_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('voucher_id')
    )
    # ### end Alembic commands ###
