"""empty message

Revision ID: 43ad227bb138
Revises: 88dc6acabc25
Create Date: 2026-05-31 22:36:52.448924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ad227bb138'
down_revision = '88dc6acabc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rzerv_points',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rzerv_points',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
