"""empty message

Revision ID: 4cb573341eef
Revises: f9d0218ca90d
Create Date: 2026-04-24 19:49:56.757929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb573341eef'
down_revision = 'f9d0218ca90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serv_charge', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('serv_charge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serv_charge', sa.NUMERIC(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('serv_charge')

    # ### end Alembic commands ###
