"""empty message

Revision ID: 51a5b5e066a7
Revises: aa55f97c2b22
Create Date: 2026-08-27 20:12:53.851187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a5b5e066a7'
down_revision = 'aa55f97c2b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_fee_host', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sms_fee_gbp', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=False))
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('sms_notifications_enabled')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.drop_column('sms_fee_gbp')
        batch_op.drop_column('sms_fee_host')

    # ### end Alembic commands ###
