"""empty message

Revision ID: 53d082275109
Revises: 762d0379f514
Create Date: 2026-04-05 22:28:31.178943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d082275109'
down_revision = '762d0379f514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('ad_info',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('ad_info',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
