"""empty message

Revision ID: 56db9fc44538
Revises: af6e075ee705
Create Date: 2026-03-12 22:58:14.566501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56db9fc44538'
down_revision = 'af6e075ee705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('amenities')
        batch_op.drop_column('services')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
