"""empty message

Revision ID: 6c83d87a3297
Revises: 7954e21e29b8
Create Date: 2026-07-15 10:23:51.275341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c83d87a3297'
down_revision = '7954e21e29b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rooms')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    op.create_table('_alembic_tmp_rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('room_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('room_location', sa.VARCHAR(length=30), nullable=False),
    sa.Column('room_category', sa.VARCHAR(length=30), nullable=False),
    sa.Column('image1', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image2', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image3', sa.VARCHAR(length=20), nullable=False),
    sa.Column('short_desc', sa.VARCHAR(length=100), nullable=False),
    sa.Column('room_size', sa.VARCHAR(length=20), nullable=False),
    sa.Column('max_occupancy', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('image4', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image5', sa.VARCHAR(length=20), nullable=False),
    sa.Column('image6', sa.VARCHAR(length=20), nullable=False),
    sa.Column('usp1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('usp2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('usp3', sa.VARCHAR(length=50), nullable=True),
    sa.Column('room_country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    # ### end Alembic commands ###
