"""empty message

Revision ID: 6d10fe39cd51
Revises: 85eeecb9c990
Create Date: 2026-03-28 16:14:30.193607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d10fe39cd51'
down_revision = '85eeecb9c990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomreviews', schema=None) as batch_op:
        batch_op.alter_column('rate_us',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomreviews', schema=None) as batch_op:
        batch_op.alter_column('rate_us',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
