"""empty message

Revision ID: 6e59dff58518
Revises: 6d3e0eb01894
Create Date: 2026-05-17 00:11:09.156881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e59dff58518'
down_revision = '6d3e0eb01894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
