"""empty message

Revision ID: 762d0379f514
Revises: db0352a8a686
Create Date: 2026-04-05 20:40:15.945372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762d0379f514'
down_revision = 'db0352a8a686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('num_rooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_rooms', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
