"""empty message

Revision ID: 78ba7dd8e533
Revises: 6b71db4ef71a
Create Date: 2026-08-16 01:57:46.674489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ba7dd8e533'
down_revision = '6b71db4ef71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borough', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_rooms_borough'), ['borough'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_borough'))
        batch_op.drop_column('borough')

    # ### end Alembic commands ###
