"""empty message

Revision ID: 7a5474b06c90
Revises: 8312722fd8b5
Create Date: 2026-04-17 12:11:22.819436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5474b06c90'
down_revision = '8312722fd8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('book_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_column('total_paid')
        batch_op.drop_column('book_days')
        batch_op.drop_column('price_per_night')

    # ### end Alembic commands ###
