"""add sms_notifications_enabled

Revision ID: 7a5ee3b2282c
Revises: 4cb4ff875a7e
Create Date: 2026-08-27 20:44:41.475345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5ee3b2282c'
down_revision = '4cb4ff875a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_hostearning')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('sms_notifications_enabled')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    op.create_table('_alembic_tmp_hostearning',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('gross_amount_host', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount_gbp', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('discount_host', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('discount_gbp', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('host_earning_host', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('host_earning_gbp', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('host_currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('voucher_amount_gbp', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('voucher_amount_host', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('platform_fee_host', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_gbp', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('sms_fee_host', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('sms_fee_gbp', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###
