"""empty message

Revision ID: 7f4609d9fc7c
Revises: cc0d8120df22
Create Date: 2026-08-27 21:47:45.244837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4609d9fc7c'
down_revision = 'cc0d8120df22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_fee_host', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notification_fee_gbp', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notification_channel_used', sa.String(length=10), nullable=True))
        batch_op.drop_column('sms_fee_host')
        batch_op.drop_column('sms_fee_gbp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_channel', sa.String(length=10), nullable=False))
        batch_op.drop_column('sms_notifications_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('notification_channel')

    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_fee_gbp', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sms_fee_host', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.drop_column('notification_channel_used')
        batch_op.drop_column('notification_fee_gbp')
        batch_op.drop_column('notification_fee_host')

    # ### end Alembic commands ###
