"""empty message

Revision ID: 803f0829f6a2
Revises: 214111ca8418
Create Date: 2026-04-10 10:10:44.925613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803f0829f6a2'
down_revision = '214111ca8418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bookings')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('ad_info',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('ad_info',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('_alembic_tmp_bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('arrival', sa.DATE(), nullable=False),
    sa.Column('departure', sa.DATE(), nullable=False),
    sa.Column('num_guests', sa.INTEGER(), nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('ad_info', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('primary_guest', sa.VARCHAR(length=30), nullable=False),
    sa.Column('pguest_email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('pguest_phone', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
