"""empty message

Revision ID: 84c2a6be011b
Revises: 5cf0851b33a7
Create Date: 2026-05-07 21:43:19.723584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c2a6be011b'
down_revision = '5cf0851b33a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.String(length=5),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
