"""empty message

Revision ID: 88dc6acabc25
Revises: c21c8dc3a108
Create Date: 2026-05-31 22:28:16.591207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88dc6acabc25'
down_revision = 'c21c8dc3a108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('points_earned')

    # ### end Alembic commands ###
