"""empty message

Revision ID: 8f7eb1942f35
Revises: dcfdcab5ec80
Create Date: 2026-07-15 22:17:49.191181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7eb1942f35'
down_revision = 'dcfdcab5ec80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_exchange_rate', ['base_currency', 'target_currency'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_constraint('unique_exchange_rate', type_='unique')

    # ### end Alembic commands ###
