"""empty message

Revision ID: 95a1ab6a5955
Revises: b4cf890bf93a
Create Date: 2026-06-01 12:09:57.315440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a1ab6a5955'
down_revision = 'b4cf890bf93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
