"""empty message

Revision ID: 96e5e75e3f45
Revises: 8c557349918d
Create Date: 2026-01-07 22:15:10.669713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e5e75e3f45'
down_revision = '8c557349918d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
