"""empty message

Revision ID: 99f24c06f7a2
Revises: 29a3307709a3
Create Date: 2026-05-25 11:52:24.652523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f24c06f7a2'
down_revision = '29a3307709a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['booking_id'])
        batch_op.create_unique_constraint(None, ['payment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
