"""empty message

Revision ID: 99f9312d4d64
Revises: 3faccc5b6bd6
Create Date: 2026-03-14 16:48:43.852816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f9312d4d64'
down_revision = '3faccc5b6bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.alter_column('car',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('internet',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.alter_column('internet',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('car',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
