"""empty message

Revision ID: 9d035b0800b8
Revises: 11d9061deb88
Create Date: 2026-03-11 22:19:49.351960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d035b0800b8'
down_revision = '11d9061deb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image4', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('image6', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('services', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('services')
        batch_op.drop_column('image6')
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')

    # ### end Alembic commands ###
