"""empty message

Revision ID: 9f5871fdc32e
Revises: cb870851ae71
Create Date: 2026-06-15 18:20:29.370840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5871fdc32e'
down_revision = 'cb870851ae71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_message_rcver_id', 'user', ['receiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_rcver_id', type_='foreignkey')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
