"""empty message

Revision ID: a237357f6a0b
Revises: 3fdbc80ce19b
Create Date: 2026-01-05 19:35:10.236114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a237357f6a0b'
down_revision = '3fdbc80ce19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('terms',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('terms',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
