"""empty message

Revision ID: a46661927b66
Revises: 9f5871fdc32e
Create Date: 2026-06-19 20:58:47.516990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46661927b66'
down_revision = '9f5871fdc32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###
