"""empty message

Revision ID: a970f39e886b
Revises: 9fe62c6995ab
Create Date: 2026-03-27 10:16:30.911933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a970f39e886b'
down_revision = '9fe62c6995ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usp1', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('usp2', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('usp3', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('usp3')
        batch_op.drop_column('usp2')
        batch_op.drop_column('usp1')

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rate_us', sa.INTEGER(), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('message', sa.VARCHAR(length=120), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
