"""empty message

Revision ID: aa55f97c2b22
Revises: 01d0a6ab19e9
Create Date: 2026-08-23 14:58:18.870947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa55f97c2b22'
down_revision = '01d0a6ab19e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_fee_guest', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gateway_fee_gbp', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gateway_channel', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('gateway_reference', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('gateway_reference')
        batch_op.drop_column('gateway_channel')
        batch_op.drop_column('gateway_fee_gbp')
        batch_op.drop_column('gateway_fee_guest')

    # ### end Alembic commands ###
