"""empty message

Revision ID: b0fe973c769b
Revises: 1e232807b211
Create Date: 2026-01-17 20:57:42.298119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fe973c769b'
down_revision = '1e232807b211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('aboutme',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('aboutme',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
