"""empty message

Revision ID: b4cf890bf93a
Revises: 43ad227bb138
Create Date: 2026-05-31 22:44:43.999561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cf890bf93a'
down_revision = '43ad227bb138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
