"""empty message

Revision ID: b83ff4eeedf1
Revises: d2832746f111
Create Date: 2026-04-17 21:40:19.131809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83ff4eeedf1'
down_revision = 'd2832746f111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('voucher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('voucher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
