"""empty message

Revision ID: ba0a196f655b
Revises: 7f4609d9fc7c
Create Date: 2026-08-27 21:49:58.689495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0a196f655b'
down_revision = '7f4609d9fc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_hostearning')
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_fee_host', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notification_fee_gbp', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notification_channel_used', sa.String(length=10), nullable=True))
        batch_op.drop_column('sms_fee_gbp')
        batch_op.drop_column('sms_fee_host')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_channel', sa.String(length=10), nullable=True))
        batch_op.drop_column('sms_notifications_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('notification_channel')

    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_fee_host', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sms_fee_gbp', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.drop_column('notification_channel_used')
        batch_op.drop_column('notification_fee_gbp')
        batch_op.drop_column('notification_fee_host')

    op.create_table('_alembic_tmp_hostearning',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('gross_amount_host', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount_gbp', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('discount_host', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('discount_gbp', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('host_earning_host', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('host_earning_gbp', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('host_currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('voucher_amount_gbp', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('voucher_amount_host', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('platform_fee_host', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_gbp', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('notification_fee_host', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('notification_fee_gbp', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('notification_channel_used', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###
