"""empty message

Revision ID: c21c8dc3a108
Revises: 05a74461507a
Create Date: 2026-05-31 22:09:42.424085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21c8dc3a108'
down_revision = '05a74461507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('rzerv_points')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rzerv_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rzerv_points')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rzerv_points', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
