"""empty message

Revision ID: c4853d3123d5
Revises: 56db9fc44538
Create Date: 2026-03-13 10:20:55.211314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4853d3123d5'
down_revision = '56db9fc44538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('amenities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sleeping', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hot_water', sa.VARCHAR(length=10), nullable=False),
    sa.Column('tv', sa.VARCHAR(length=10), nullable=False),
    sa.Column('kitchen', sa.VARCHAR(length=10), nullable=False),
    sa.Column('towels', sa.VARCHAR(length=10), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id'),
    sa.UniqueConstraint('sleeping')
    )
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resto', sa.VARCHAR(length=20), nullable=False),
    sa.Column('bar', sa.VARCHAR(length=10), nullable=False),
    sa.Column('spa', sa.VARCHAR(length=10), nullable=False),
    sa.Column('shop', sa.VARCHAR(length=10), nullable=False),
    sa.Column('concierge', sa.VARCHAR(length=10), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resto'),
    sa.UniqueConstraint('room_id')
    )
    # ### end Alembic commands ###
