"""empty message

Revision ID: d2832746f111
Revises: aec037f45e32
Create Date: 2026-04-17 15:14:51.469175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2832746f111'
down_revision = 'aec037f45e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymid', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['paymid'])
        batch_op.create_foreign_key(None, 'payments', ['paymid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('paymid')

    # ### end Alembic commands ###
