"""empty message

Revision ID: d2a066642779
Revises: 146722d01960
Create Date: 2026-03-14 12:20:48.388794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a066642779'
down_revision = '146722d01960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.alter_column('internet',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomextra', schema=None) as batch_op:
        batch_op.alter_column('internet',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
