"""empty message

Revision ID: d440df6c72d5
Revises: 50ef624d9e27
Create Date: 2026-05-31 00:24:02.419494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd440df6c72d5'
down_revision = '50ef624d9e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'deals', ['deal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deal_id')

    # ### end Alembic commands ###
