"""empty message

Revision ID: d7782d35ddbe
Revises: dca3c25c76a1
Create Date: 2026-03-28 21:25:28.639918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7782d35ddbe'
down_revision = 'dca3c25c76a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomreviews', schema=None) as batch_op:
        batch_op.alter_column('rate_us',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomreviews', schema=None) as batch_op:
        batch_op.alter_column('rate_us',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
