"""empty message

Revision ID: db0352a8a686
Revises: d7782d35ddbe
Create Date: 2026-04-02 12:09:18.883480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0352a8a686'
down_revision = 'd7782d35ddbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_guest', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('pguest_email', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('pguest_phone', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('pguest_phone')
        batch_op.drop_column('pguest_email')
        batch_op.drop_column('primary_guest')

    # ### end Alembic commands ###
