"""empty message

Revision ID: e73bc1ca5e34
Revises: 13e96be0b692
Create Date: 2026-05-25 13:18:01.536928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73bc1ca5e34'
down_revision = '13e96be0b692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostearning', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
