"""empty message

Revision ID: ecaa326465e2
Revises: 5f153dd6f9fc
Create Date: 2026-06-24 19:03:38.821652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecaa326465e2'
down_revision = '5f153dd6f9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('is_flagged')

    # ### end Alembic commands ###
