"""empty message

Revision ID: f1993703bb90
Revises: 1fda0b7a245e
Create Date: 2026-01-15 12:37:38.871810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1993703bb90'
down_revision = '1fda0b7a245e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('aboutme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aboutme', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
