"""empty message

Revision ID: ffdf3a4ba260
Revises: 70c1019ee3cb
Create Date: 2026-05-10 21:18:24.631072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdf3a4ba260'
down_revision = '70c1019ee3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('voucher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('voucher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
